version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      # ESM-only
      - dependency-name: registry-url
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
